-- Default monitor rule: every output at its preferred mode, auto-placed, scale from PPI.
-- Per-monitor overrides are generated by the settings panel.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
