[package]
name = "sysmon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "eDEX-DE system statistics and privacy probes"

[dependencies]
libc = { workspace = true }
sysinfo = { workspace = true }
tracing = { workspace = true }
