[package]
name = "launcher"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "eDEX-DE app launcher"

[dependencies]
hypr = { path = "../hypr" }
fuzzy-matcher = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
xdg = { workspace = true }
rustix = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
