//! Make Qt and GTK applications follow the eDEX theme: a qt6ct palette (Fusion style), GTK 3/4
//! settings and accent colours, and the GNOME interface keys that portals and libadwaita read.
//!
//! Files that already exist without the eDEX marker belong to the user and are left alone.

use std::path::{Path, PathBuf};

use tracing::{info, warn};
use ui::{geometry::Color, Theme};

const MARK: &str = "Generated by eDEX-DE";
pub const ICON_THEME: &str = "Papirus-Dark";
pub const GTK3_THEME: &str = "adw-gtk3-dark";
pub const CURSOR_THEME: &str = "Adwaita";

fn hex(c: Color) -> String {
    let b = |v: f32| (v.clamp(0.0, 1.0) * 255.0).round() as u8;
    format!("#{:02x}{:02x}{:02x}", b(c[0]), b(c[1]), b(c[2]))
}

fn mix(a: Color, b: Color, t: f32) -> Color {
    [
        a[0] + (b[0] - a[0]) * t,
        a[1] + (b[1] - a[1]) * t,
        a[2] + (b[2] - a[2]) * t,
        1.0,
    ]
}

const BLACK: Color = [0.0, 0.0, 0.0, 1.0];
const WHITE: Color = [1.0, 1.0, 1.0, 1.0];

/// QPalette roles in qt6ct order (Qt 6.6+ adds Accent at the end).
fn qt_roles(t: &Theme, disabled: bool) -> Vec<String> {
    let base = mix(t.background, BLACK, 0.15);
    let window = t.panel_bg;
    let button = mix(t.panel_bg, t.border, 0.12);
    let text = if disabled {
        mix(t.text_primary, window, 0.55)
    } else {
        t.text_primary
    };
    let highlight = if disabled {
        mix(t.accent, window, 0.6)
    } else {
        t.accent
    };
    [
        text,                          // WindowText
        button,                        // Button
        mix(button, WHITE, 0.25),      // Light
        mix(button, WHITE, 0.12),      // Midlight
        mix(window, BLACK, 0.5),       // Dark
        mix(window, t.border, 0.35),   // Mid
        text,                          // Text
        WHITE,                         // BrightText
        text,                          // ButtonText
        base,                          // Base
        window,                        // Window
        BLACK,                         // Shadow
        highlight,                     // Highlight
        mix(t.background, BLACK, 0.3), // HighlightedText
        t.accent,                      // Link
        t.text_secondary,              // LinkVisited
        mix(base, t.border, 0.08),     // AlternateBase
        window,                        // NoRole
        t.panel_bg,                    // ToolTipBase
        t.text_primary,                // ToolTipText
        t.text_dim,                    // PlaceholderText
        t.accent,                      // Accent
    ]
    .into_iter()
    .map(hex)
    .collect()
}

fn rgb(c: Color) -> String {
    let b = |v: f32| (v.clamp(0.0, 1.0) * 255.0).round() as u8;
    format!("{},{},{}", b(c[0]), b(c[1]), b(c[2]))
}

/// Name of the KDE colour scheme written to `$XDG_DATA_HOME/color-schemes/`.
const KDE_SCHEME: &str = "eDEX";

/// The `[Colors:*]` groups of a KDE colour scheme.
fn kde_colors(t: &Theme) -> String {
    let view = mix(t.background, BLACK, 0.15);
    let window = t.panel_bg;
    let button = mix(t.panel_bg, t.border, 0.12);
    let header = mix(t.panel_bg, t.border, 0.1);
    let on_accent = mix(t.background, BLACK, 0.3);
    let set = |name: &str, bg: Color, alt: Color, fg: Color| {
        format!(
            "[Colors:{name}]\nBackgroundNormal={}\nBackgroundAlternate={}\nForegroundNormal={}\nForegroundInactive={}\nForegroundActive={}\nForegroundLink={}\nForegroundVisited={}\nForegroundNegative={}\nForegroundNeutral={}\nForegroundPositive={}\nDecorationFocus={}\nDecorationHover={}\n\n",
            rgb(bg),
            rgb(alt),
            rgb(fg),
            rgb(t.text_dim),
            rgb(t.accent),
            rgb(t.accent),
            rgb(t.text_secondary),
            rgb(t.error),
            rgb(t.warning),
            rgb(t.palette[2]),
            rgb(t.accent),
            rgb(t.border),
        )
    };
    let mut s = String::new();
    s.push_str(&set(
        "View",
        view,
        mix(view, t.border, 0.08),
        t.text_primary,
    ));
    s.push_str(&set(
        "Window",
        window,
        mix(window, t.border, 0.08),
        t.text_primary,
    ));
    s.push_str(&set(
        "Button",
        button,
        mix(button, WHITE, 0.05),
        t.text_primary,
    ));
    s.push_str(&set(
        "Selection",
        t.accent,
        mix(t.accent, BLACK, 0.2),
        on_accent,
    ));
    s.push_str(&set("Tooltip", t.panel_bg, t.panel_bg, t.text_primary));
    s.push_str(&set(
        "Complementary",
        mix(t.background, BLACK, 0.3),
        t.background,
        t.text_primary,
    ));
    s.push_str(&set("Header", header, header, t.text_primary));
    s
}

/// A KDE colour scheme file. Kirigami apps (Discover) only follow the scheme named in
/// `[UiSettings] ColorScheme`; without it they fall back to Breeze whatever kdeglobals says.
fn kde_scheme(t: &Theme) -> String {
    format!(
        "# {MARK} from the '{}' theme (remove this line to keep your changes)\n{}[General]\nName={KDE_SCHEME}\nColorScheme={KDE_SCHEME}\n",
        t.name,
        kde_colors(t)
    )
}

/// kdeglobals: colours for KColorScheme readers, plus the scheme, fonts and icons.
fn kdeglobals(t: &Theme, font: &str, font_pt: u32) -> String {
    let mut s = format!(
        "# {MARK} from the '{}' theme (remove this line to keep your changes)\n{}",
        t.name,
        kde_colors(t)
    );
    s.push_str(&format!(
        "[General]\nColorScheme={KDE_SCHEME}\nfont={font},{font_pt},-1,5,400,0,0,0,0,0\nfixed={font},{font_pt},-1,5,400,0,0,0,0,0\n\n[Icons]\nTheme={ICON_THEME}\n\n[KDE]\nwidgetStyle=Fusion\n\n[UiSettings]\nColorScheme={KDE_SCHEME}\n"
    ));
    s
}

/// Files to write: relative paths are under `$XDG_CONFIG_HOME`, absolute ones under `data_dir`.
pub fn render(
    config_dir: &Path,
    data_dir: &Path,
    theme: &Theme,
    font: &str,
    font_pt: u32,
) -> Vec<(PathBuf, String)> {
    let mut out = Vec::new();
    let active = qt_roles(theme, false).join(", ");
    let disabled = qt_roles(theme, true).join(", ");
    out.push((
        PathBuf::from("qt6ct/colors/edex.conf"),
        format!(
            "; {MARK} from the '{}' theme\n[ColorScheme]\nactive_colors={active}\ndisabled_colors={disabled}\ninactive_colors={active}\n",
            theme.name
        ),
    ));
    // Qt 6 QFont::toString layout: family, size, pixel size, style hint, weight, style, ...
    let qfont = |pt: u32| format!("\"{font},{pt},-1,5,400,0,0,0,0,0,0,0,0,0,0,1\"");
    out.push((
        PathBuf::from("qt6ct/qt6ct.conf"),
        format!(
            "; {MARK}; edit with qt6ct (remove this line to keep your changes)\n[Appearance]\ncolor_scheme_path={}\ncustom_palette=true\nicon_theme={ICON_THEME}\nstandard_dialogs=xdgdesktopportal\nstyle=Fusion\n\n[Fonts]\nfixed={}\ngeneral={}\n",
            config_dir.join("qt6ct/colors/edex.conf").display(),
            qfont(font_pt),
            qfont(font_pt)
        ),
    ));
    out.push((
        PathBuf::from("kdeglobals"),
        kdeglobals(theme, font, font_pt),
    ));
    out.push((
        data_dir.join(format!("color-schemes/{KDE_SCHEME}.colors")),
        kde_scheme(theme),
    ));
    let gtk_settings = |theme_line: &str| {
        format!(
            "# {MARK} (remove this line to keep your changes)\n[Settings]\n{theme_line}gtk-icon-theme-name={ICON_THEME}\ngtk-cursor-theme-name={CURSOR_THEME}\ngtk-font-name={font} {font_pt}\n"
        )
    };
    out.push((
        PathBuf::from("gtk-3.0/settings.ini"),
        gtk_settings(&format!(
            "gtk-theme-name={GTK3_THEME}\ngtk-application-prefer-dark-theme=1\n"
        )),
    ));
    // No prefer-dark here: libadwaita rejects it and takes the gsettings color-scheme instead.
    out.push((PathBuf::from("gtk-4.0/settings.ini"), gtk_settings("")));
    let t = theme;
    let window = hex(t.panel_bg);
    let view = hex(mix(t.background, BLACK, 0.15));
    let fg = hex(t.text_primary);
    let accent = hex(t.accent);
    let accent_fg = hex(mix(t.background, BLACK, 0.3));
    let header = hex(mix(t.panel_bg, t.border, 0.1));
    let card = hex(mix(t.panel_bg, t.border, 0.06));
    // adw-gtk3 and libadwaita read the same named colours; GTK >= 4.16 also takes the variables.
    let named = format!(
        "/* {MARK} from the '{}' theme (remove this line to keep your changes) */\n\
@define-color accent_color {accent};\n@define-color accent_bg_color {accent};\n@define-color accent_fg_color {accent_fg};\n\
@define-color window_bg_color {window};\n@define-color window_fg_color {fg};\n\
@define-color view_bg_color {view};\n@define-color view_fg_color {fg};\n\
@define-color headerbar_bg_color {header};\n@define-color headerbar_fg_color {fg};\n\
@define-color sidebar_bg_color {header};\n@define-color sidebar_fg_color {fg};\n\
@define-color card_bg_color {card};\n@define-color card_fg_color {fg};\n\
@define-color popover_bg_color {card};\n@define-color popover_fg_color {fg};\n\
@define-color dialog_bg_color {card};\n@define-color dialog_fg_color {fg};\n",
        t.name
    );
    let vars = format!(
        ":root {{\n  --accent-color: {accent};\n  --accent-bg-color: {accent};\n  --accent-fg-color: {accent_fg};\n  --window-bg-color: {window};\n  --window-fg-color: {fg};\n  --view-bg-color: {view};\n  --view-fg-color: {fg};\n  --headerbar-bg-color: {header};\n  --headerbar-fg-color: {fg};\n  --sidebar-bg-color: {header};\n  --sidebar-fg-color: {fg};\n  --card-bg-color: {card};\n  --card-fg-color: {fg};\n  --popover-bg-color: {card};\n  --popover-fg-color: {fg};\n  --dialog-bg-color: {card};\n  --dialog-fg-color: {fg};\n}}\n"
    );
    out.push((PathBuf::from("gtk-3.0/gtk.css"), named.clone()));
    out.push((PathBuf::from("gtk-4.0/gtk.css"), named + &vars));
    out
}

/// Ours to overwrite: missing, or carrying the eDEX marker.
fn writable(path: &Path) -> bool {
    match std::fs::read_to_string(path) {
        Ok(s) => s.lines().next().is_some_and(|l| l.contains(MARK)),
        Err(_) => true,
    }
}

/// Write the files under `config_dir` / `data_dir` and set the GNOME interface keys.
pub fn apply(config_dir: &Path, data_dir: &Path, theme: &Theme, font: &str, font_pt: u32) {
    let mut written = 0;
    for (rel, contents) in render(config_dir, data_dir, theme, font, font_pt) {
        let path = config_dir.join(&rel);
        if !writable(&path) {
            continue;
        }
        if let Some(parent) = path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        let tmp = path.with_extension("edex-tmp");
        match std::fs::write(&tmp, contents).and_then(|_| std::fs::rename(&tmp, &path)) {
            Ok(()) => written += 1,
            Err(e) => warn!("theming {}: {e}", path.display()),
        }
    }
    // GTK 4 / libadwaita (and the settings portal) read these rather than settings.ini.
    let keys: [(&str, String); 6] = [
        ("color-scheme", "prefer-dark".into()),
        ("gtk-theme", GTK3_THEME.into()),
        ("icon-theme", ICON_THEME.into()),
        ("cursor-theme", CURSOR_THEME.into()),
        ("font-name", format!("{font} {font_pt}")),
        ("monospace-font-name", format!("{font} {font_pt}")),
    ];
    std::thread::spawn(move || {
        for (k, v) in keys {
            let _ = std::process::Command::new("gsettings")
                .args(["set", "org.gnome.desktop.interface", k, &v])
                .stdout(std::process::Stdio::null())
                .stderr(std::process::Stdio::null())
                .status();
        }
    });
    info!(theme = %theme.name, files = written, "applied theme to Qt and GTK apps");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_toolkit_files_from_the_theme() {
        let theme = ui::theme::builtin_tron();
        let files = render(
            Path::new("/home/u/.config"),
            Path::new("/home/u/.local/share"),
            &theme,
            "JetBrainsMono Nerd Font",
            10,
        );
        let get = |p: &str| {
            files
                .iter()
                .find(|(path, _)| path == Path::new(p))
                .map(|(_, c)| c.clone())
                .unwrap_or_else(|| panic!("{p} missing"))
        };
        let colors = get("qt6ct/colors/edex.conf");
        let active = colors
            .lines()
            .find_map(|l| l.strip_prefix("active_colors="))
            .unwrap();
        assert_eq!(active.split(", ").count(), 22);
        assert!(active
            .split(", ")
            .all(|c| c.len() == 7 && c.starts_with('#')));
        let qt = get("qt6ct/qt6ct.conf");
        assert!(qt.contains("icon_theme=Papirus-Dark"));
        assert!(qt.contains("color_scheme_path=/home/u/.config/qt6ct/colors/edex.conf"));
        assert!(!get("gtk-3.0/gtk.css").contains(":root"));
        let kde = get("kdeglobals");
        assert!(kde.contains("[Colors:View]") && kde.contains("[Colors:Selection]"));
        assert!(kde.contains("[Icons]\nTheme=Papirus-Dark"));
        assert!(kde.contains("[UiSettings]\nColorScheme=eDEX"));
        let scheme = get("/home/u/.local/share/color-schemes/eDEX.colors");
        assert!(scheme.contains("[Colors:Window]") && scheme.contains("Name=eDEX"));
        assert!(get("gtk-3.0/settings.ini").contains("gtk-theme-name=adw-gtk3-dark"));
        assert!(!get("gtk-4.0/settings.ini").contains("gtk-theme-name"));
        assert!(!get("gtk-4.0/settings.ini").contains("prefer-dark"));
        assert!(get("gtk-3.0/settings.ini").contains("gtk-application-prefer-dark-theme=1"));
        assert!(
            get("gtk-4.0/gtk.css").contains(&format!("--accent-bg-color: {}", hex(theme.accent)))
        );
        assert!(files
            .iter()
            .all(|(_, c)| c.lines().next().unwrap().contains(MARK)));
    }

    #[test]
    fn leaves_user_files_alone() {
        let dir = tempfile::tempdir().unwrap();
        let own = dir.path().join("qt6ct/qt6ct.conf");
        std::fs::create_dir_all(own.parent().unwrap()).unwrap();
        std::fs::write(&own, "[Appearance]\nstyle=kvantum\n").unwrap();
        assert!(!writable(&own));
        let ours = dir.path().join("gtk-3.0/settings.ini");
        std::fs::create_dir_all(ours.parent().unwrap()).unwrap();
        std::fs::write(&ours, format!("# {MARK}\n[Settings]\n")).unwrap();
        assert!(writable(&ours));
        assert!(writable(&dir.path().join("missing.conf")));
    }
}
