[package]
name = "renderer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "eDEX-DE wgpu GPU renderer"

[dependencies]
ui = { path = "../ui" }
wgpu = { workspace = true }
glyphon = { workspace = true }
pollster = { workspace = true }
raw-window-handle = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
