//! Generate the Lua fragment Hyprland loads from the user's eDEX settings.

use std::{fs, path::Path};

use anyhow::{Context, Result};

use crate::config::Config;

fn lua_str(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Render `generated.lua`.
/// Screen off/on through Hyprland (0.55+ dispatch takes a Lua expression).
const DPMS_OFF: &str = r#"hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'"#;
const DPMS_ON: &str = r#"hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'"#;

pub fn render_lua(config: &Config) -> String {
    let mut out = String::new();
    out.push_str("-- Generated by eDEX-DE settings. Do not edit: changes are overwritten.\n");
    out.push_str("-- Loaded after the system config, before ~/.config/hypr/user.lua.\n\n");
    for m in &config.display.monitors {
        if m.disabled {
            out.push_str(&format!(
                "hl.monitor({{ output = {}, disabled = true }})\n",
                lua_str(&m.name)
            ));
        } else {
            out.push_str(&format!(
                "hl.monitor({{ output = {}, mode = {}, position = {}, scale = {}, transform = {} }})\n",
                lua_str(&m.name),
                lua_str(&m.mode),
                lua_str(&m.position),
                m.scale,
                m.transform
            ));
        }
    }
    out.push_str("\nhl.config({\n");
    out.push_str(&format!(
        "    general = {{ gaps_in = {}, gaps_out = {}, border_size = {}, layout = {} }},\n",
        config.wm.gaps_in,
        config.wm.gaps_out,
        config.wm.border,
        lua_str(&config.wm.layout)
    ));
    out.push_str(&format!(
        "    decoration = {{ rounding = {}, blur = {{ enabled = {} }} }},\n",
        config.wm.rounding, config.wm.blur
    ));
    out.push_str(&format!(
        "    animations = {{ enabled = {} }},\n",
        config.wm.animations
    ));
    out.push_str(&format!(
        "    input = {{ kb_layout = {}, kb_variant = {}, kb_options = {}, repeat_rate = {}, repeat_delay = {}, sensitivity = {}, touchpad = {{ natural_scroll = {}, tap_to_click = {} }} }},\n",
        lua_str(&config.input.kb_layout),
        lua_str(&config.input.kb_variant),
        lua_str(&config.input.kb_options),
        config.input.repeat_rate,
        config.input.repeat_delay,
        config.input.sensitivity,
        config.input.natural_scroll,
        config.input.tap_to_click
    ));
    out.push_str("})\n");
    out
}

/// Render `hypridle.conf` (hyprlang; hypridle has its own config format).
pub fn render_hypridle(config: &Config, lock_cmd: &str) -> String {
    let p = &config.power;
    let mut out = String::new();
    out.push_str("# Generated by eDEX-DE settings.\n");
    out.push_str("general {\n");
    out.push_str(&format!("    lock_cmd = pidof hyprlock || {lock_cmd}\n"));
    if p.lock_on_sleep {
        out.push_str("    before_sleep_cmd = loginctl lock-session\n");
    }
    out.push_str(&format!("    after_sleep_cmd = {DPMS_ON}\n"));
    out.push_str("    ignore_dbus_inhibit = false\n}\n\n");
    if p.dim_after > 0 {
        out.push_str(&format!(
            "listener {{\n    timeout = {}\n    on-timeout = brightnessctl -s set 10%\n    on-resume = brightnessctl -r\n}}\n\n",
            p.dim_after
        ));
    }
    if p.lock_after > 0 {
        out.push_str(&format!(
            "listener {{\n    timeout = {}\n    on-timeout = loginctl lock-session\n}}\n\n",
            p.lock_after
        ));
    }
    if p.dpms_after > 0 {
        out.push_str(&format!(
            "listener {{\n    timeout = {}\n    on-timeout = {DPMS_OFF}\n    on-resume = {DPMS_ON}\n}}\n\n",
            p.dpms_after
        ));
    }
    if p.suspend_after > 0 {
        out.push_str(&format!(
            "listener {{\n    timeout = {}\n    on-timeout = systemctl suspend\n}}\n",
            p.suspend_after
        ));
    }
    out
}

/// Write both generated files under the config directory.
pub fn export(config: &Config, config_dir: &Path, lock_cmd: &str) -> Result<()> {
    let dir = config_dir.join("hypr");
    fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;
    fs::write(dir.join("generated.lua"), render_lua(config))?;
    fs::write(dir.join("hypridle.conf"), render_hypridle(config, lock_cmd))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn golden_lua() {
        let mut c = Config::default();
        c.display.monitors.push(crate::config::Monitor {
            name: "DP-1".into(),
            mode: "2560x1440@144".into(),
            position: "0x0".into(),
            scale: 1.25,
            transform: 0,
            disabled: false,
        });
        insta::assert_snapshot!(render_lua(&c));
        insta::assert_snapshot!(render_hypridle(&c, "hyprlock"));
    }
}
