//! labwc configuration generated from the eDEX settings: `rc.xml` (key bindings mirroring
//! Hyprland's `binds.lua`, the window rule that tiles windows into the terminal slot, keyboard
//! repeat, touchpad and pointer), `environment` (the XKB layout) and a small root menu.
//!
//! The session runs `labwc -C ~/.config/edex-de/labwc` so these files are the whole labwc
//! configuration; `edex-de labwc-config` writes them before the first start.

use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};

use crate::config::Config;

/// `~/.config/edex-de/labwc`.
pub fn config_dir() -> PathBuf {
    crate::paths::config_dir().join("labwc")
}

fn xml(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn yes(b: bool) -> &'static str {
    if b {
        "yes"
    } else {
        "no"
    }
}

/// The program that opens a terminal window (the first word of the launcher's terminal
/// command, e.g. `foot` or `kitty`).
fn terminal_program(config: &Config) -> String {
    let t = config.launcher.terminal_command.trim();
    let t = t.strip_suffix(" -e").unwrap_or(t);
    if t.is_empty() {
        "foot".into()
    } else {
        t.to_string()
    }
}

/// (key, action XML) pairs. `ipc` actions run `edex-de ipc …`.
fn binds(config: &Config) -> Vec<(String, String)> {
    let exec = |cmd: &str| format!(r#"<action name="Execute" command="{}" />"#, xml(cmd));
    let ipc = |args: &str| exec(&format!("edex-de ipc {args}"));
    let action = |name: &str| format!(r#"<action name="{name}" />"#);
    let mut b: Vec<(String, String)> = vec![
        // Shell overlays.
        ("W-space".into(), ipc("toggle launcher")),
        ("W-comma".into(), ipc("toggle settings")),
        ("W-p".into(), ipc("toggle privacy")),
        ("W-n".into(), ipc("toggle notifications")),
        ("W-Escape".into(), ipc("toggle power")),
        ("W-Return".into(), ipc("focus terminal")),
        ("W-F1".into(), ipc("focus filesystem")),
        // Applications.
        ("W-S-Return".into(), exec(&terminal_program(config))),
        // Windows: the shell's controls, so the tab strip stays in step.
        ("W-q".into(), action("Close")),
        ("W-S-q".into(), action("Kill")),
        ("W-f".into(), ipc("action maximize")),
        ("W-S-f".into(), action("ToggleFullscreen")),
        ("W-m".into(), action("Iconify")),
        ("W-C-f".into(), ipc("action side-panels")),
        // Float / tile: labwc's maximize is what fits a window into the terminal slot.
        ("W-v".into(), action("ToggleMaximize")),
        ("W-Tab".into(), action("NextWindow")),
        ("W-S-Tab".into(), action("PreviousWindow")),
        ("A-Tab".into(), action("NextWindow")),
        ("A-F4".into(), action("Close")),
        (
            "W-S-r".into(),
            format!("{}{}", action("Reconfigure"), ipc("reload")),
        ),
        // Media keys.
        ("XF86AudioRaiseVolume".into(), ipc("audio volume +5")),
        ("XF86AudioLowerVolume".into(), ipc("audio volume -5")),
        ("XF86AudioMute".into(), ipc("audio mute")),
        ("XF86AudioMicMute".into(), ipc("audio mic-mute")),
        ("XF86MonBrightnessUp".into(), ipc("brightness +10")),
        ("XF86MonBrightnessDown".into(), ipc("brightness -10")),
    ];
    for (k, dir) in [
        ("Left", "left"),
        ("Right", "right"),
        ("Up", "up"),
        ("Down", "down"),
    ] {
        b.push((
            format!("W-S-{k}"),
            format!(r#"<action name="MoveToEdge" direction="{dir}" />"#),
        ));
    }
    b
}

/// The key bindings as "keys  →  action" lines (Settings → Window manager).
pub fn bind_lines(config: &Config) -> Vec<String> {
    let mut lines = vec!["Super (tap)  →  launcher".to_string()];
    for (key, actions) in binds(config) {
        let what = actions
            .split("command=\"")
            .nth(1)
            .and_then(|r| r.split('"').next())
            .map(|c| c.replace("&amp;", "&").replace("&quot;", "\""))
            .or_else(|| {
                actions
                    .split("name=\"")
                    .nth(1)
                    .and_then(|r| r.split('"').next())
                    .map(String::from)
            })
            .unwrap_or_default();
        lines.push(format!(
            "{}  →  {what}",
            key.replace("W-", "Super+")
                .replace("S-", "Shift+")
                .replace("C-", "Ctrl+")
                .replace("A-", "Alt+")
        ));
    }
    lines
}

/// Render `rc.xml`.
pub fn render_rc_xml(config: &Config) -> String {
    let w = &config.wm;
    let i = &config.input;
    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\"?>\n");
    out.push_str("<!-- Generated by eDEX-DE settings (Settings → Window manager). Do not edit:\n");
    out.push_str("     changes are overwritten. -->\n");
    out.push_str("<labwc_config>\n");
    out.push_str("  <core>\n    <decoration>server</decoration>\n");
    out.push_str(&format!("    <gap>{}</gap>\n", w.gaps_out));
    out.push_str("  </core>\n");
    // The shell draws the frame: tiled (maximized) windows get no title bar.
    out.push_str("  <theme>\n    <maximizedDecoration>none</maximizedDecoration>\n");
    out.push_str(&format!(
        "    <cornerRadius>{}</cornerRadius>\n",
        w.rounding
    ));
    let font = if config.appearance.font.is_empty() {
        "JetBrainsMono Nerd Font"
    } else {
        config.appearance.font.as_str()
    };
    out.push_str(&format!(
        "    <font><name>{}</name><size>10</size></font>\n",
        xml(font)
    ));
    out.push_str("  </theme>\n");
    // One desktop: the shell's top bar has no labwc workspace list.
    out.push_str("  <desktops number=\"1\" />\n");
    // Space between the terminal slot and the windows in it.
    if w.gaps_out > 0 {
        out.push_str(&format!(
            "  <margin top=\"{0}\" bottom=\"{0}\" left=\"{0}\" right=\"{0}\" />\n",
            w.gaps_out
        ));
    }
    out.push_str("  <focus>\n    <followMouse>no</followMouse>\n    <raiseOnFocus>yes</raiseOnFocus>\n  </focus>\n");
    out.push_str("  <placement>\n    <policy>center</policy>\n  </placement>\n");
    out.push_str("  <keyboard>\n");
    out.push_str(&format!(
        "    <repeatRate>{}</repeatRate>\n    <repeatDelay>{}</repeatDelay>\n",
        i.repeat_rate, i.repeat_delay
    ));
    // Tapping Super opens the launcher (on release, not when Super is part of a combination).
    out.push_str(
        "    <keybind key=\"Super_L\" onRelease=\"yes\"><action name=\"Execute\" command=\"edex-de ipc toggle launcher\" /></keybind>\n",
    );
    for (key, actions) in binds(config) {
        out.push_str(&format!("    <keybind key=\"{key}\">{actions}</keybind>\n"));
    }
    out.push_str("  </keyboard>\n");
    out.push_str("  <mouse>\n    <default />\n  </mouse>\n");
    out.push_str("  <libinput>\n    <device category=\"default\">\n");
    out.push_str(&format!(
        "      <naturalScroll>{}</naturalScroll>\n",
        yes(i.natural_scroll)
    ));
    out.push_str(&format!("      <tap>{}</tap>\n", yes(i.tap_to_click)));
    out.push_str(&format!(
        "      <pointerSpeed>{:.2}</pointerSpeed>\n",
        i.sensitivity.clamp(-1.0, 1.0)
    ));
    out.push_str("    </device>\n  </libinput>\n");
    // Every normal window tiles into the terminal slot (labwc fits maximized windows into the
    // area the shell's reserver surfaces leave); dialogs float.
    out.push_str("  <windowRules>\n");
    out.push_str("    <windowRule identifier=\"*\" type=\"normal\">\n      <action name=\"Maximize\" />\n    </windowRule>\n");
    out.push_str("  </windowRules>\n");
    out.push_str("</labwc_config>\n");
    out
}

/// Render `environment`: labwc reads the keyboard layout from XKB_DEFAULT_* variables.
pub fn render_environment(config: &Config) -> String {
    let i = &config.input;
    let mut out = String::from("# Generated by eDEX-DE settings.\n");
    let layout = if i.kb_layout.is_empty() {
        "us"
    } else {
        i.kb_layout.as_str()
    };
    out.push_str(&format!("XKB_DEFAULT_LAYOUT={layout}\n"));
    if !i.kb_variant.is_empty() {
        out.push_str(&format!("XKB_DEFAULT_VARIANT={}\n", i.kb_variant));
    }
    if !i.kb_options.is_empty() {
        out.push_str(&format!("XKB_DEFAULT_OPTIONS={}\n", i.kb_options));
    }
    out
}

/// Render `menu.xml`: the shell covers the desktop, so this only shows on window menus.
pub fn render_menu(config: &Config) -> String {
    format!(
        "<?xml version=\"1.0\"?>\n<openbox_menu>\n  <menu id=\"root-menu\" label=\"eDEX-DE\">\n    <item label=\"Terminal\"><action name=\"Execute\" command=\"{}\" /></item>\n    <item label=\"Launcher\"><action name=\"Execute\" command=\"edex-de ipc toggle launcher\" /></item>\n    <item label=\"Reconfigure\"><action name=\"Reconfigure\" /></item>\n    <item label=\"Log out\"><action name=\"Exit\" /></item>\n  </menu>\n</openbox_menu>\n",
        xml(&terminal_program(config))
    )
}

/// Write `rc.xml`, `environment` and `menu.xml` into `dir` (atomically, each).
pub fn export(config: &Config, dir: &Path) -> Result<()> {
    fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    for (name, text) in [
        ("rc.xml", render_rc_xml(config)),
        ("environment", render_environment(config)),
        ("menu.xml", render_menu(config)),
    ] {
        let path = dir.join(name);
        let tmp = dir.join(format!(".{name}.tmp"));
        fs::write(&tmp, text).with_context(|| format!("writing {}", tmp.display()))?;
        fs::rename(&tmp, &path).with_context(|| format!("replacing {}", path.display()))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn golden_rc_xml() {
        let mut c = Config::default();
        c.launcher.terminal_command = "foot".into();
        insta::assert_snapshot!(render_rc_xml(&c));
        insta::assert_snapshot!(render_environment(&c));
    }

    #[test]
    fn rc_xml_is_well_formed_and_escaped() {
        let mut c = Config::default();
        c.appearance.font = "A & B <mono>".into();
        c.launcher.terminal_command = "kitty -e".into();
        let text = render_rc_xml(&c);
        assert!(text.contains("A &amp; B &lt;mono&gt;"));
        assert!(text.contains("command=\"kitty\""));
        let doc = roxml_check(&text);
        assert!(doc, "unbalanced tags in rc.xml");
        let dir = tempfile::tempdir().unwrap();
        export(&c, dir.path()).unwrap();
        for f in ["rc.xml", "environment", "menu.xml"] {
            assert!(dir.path().join(f).exists());
        }
    }

    /// Minimal tag balance check (the settings crate has no XML parser).
    fn roxml_check(text: &str) -> bool {
        let mut stack: Vec<String> = Vec::new();
        let mut rest = text;
        while let Some(start) = rest.find('<') {
            let end = rest[start..].find('>').map(|e| start + e).unwrap();
            let tag = &rest[start + 1..end];
            rest = &rest[end + 1..];
            if tag.starts_with('?') || tag.starts_with('!') || tag.ends_with('/') {
                continue;
            }
            if let Some(name) = tag.strip_prefix('/') {
                if stack.pop().as_deref() != Some(name) {
                    return false;
                }
            } else {
                stack.push(tag.split_whitespace().next().unwrap().to_string());
            }
        }
        stack.is_empty()
    }
}
