[package]
name = "terminal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "eDEX-DE terminal emulator (alacritty_terminal)"

[dependencies]
ui = { path = "../ui" }
alacritty_terminal = { workspace = true }
xkbcommon = { workspace = true }
unicode-width = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
